Building DAG of jobs...
Using shell: /bin/bash
Provided cores: 1
Rules claiming more threads will be scaled down.
Job counts:
	count	jobs
	1	alldata
	1	count_words_abyss
	1	count_words_isles
	1	count_words_last
	1	results
	5

[Wed Dec  5 10:37:10 2018]
rule count_words_last:
    input: data/last.txt, source/wordcount.py
    output: processed_data/last.dat
    jobid: 4

[Wed Dec  5 10:37:10 2018]
Finished job 4.
1 of 5 steps (20%) done

[Wed Dec  5 10:37:10 2018]
rule count_words_abyss:
    input: data/abyss.txt, source/wordcount.py
    output: processed_data/abyss.dat
    jobid: 2

[Wed Dec  5 10:37:10 2018]
Finished job 2.
2 of 5 steps (40%) done

[Wed Dec  5 10:37:10 2018]
rule count_words_isles:
    input: data/isles.txt, source/wordcount.py
    output: processed_data/isles.dat
    jobid: 3

[Wed Dec  5 10:37:10 2018]
Finished job 3.
3 of 5 steps (60%) done

[Wed Dec  5 10:37:10 2018]
rule results:
    input: processed_data/isles.dat, processed_data/abyss.dat, processed_data/last.dat, source/zipf_test.py
    output: results/results.txt
    jobid: 1

[Wed Dec  5 10:37:10 2018]
Error in rule results:
    jobid: 1
    output: results/results.txt

RuleException:
CalledProcessError in line 26 of /Users/jacda119/git/coderefinery/word-count/Snakefile_jd:
Command ' set -euo pipefail;  python source/zipf_test.py processed_data/isles.dat processed_data/abyss.dat processed_data/last.dat source/zipf_test.py > results/results.txt ' returned non-zero exit status 1.
  File "/Users/jacda119/git/coderefinery/word-count/Snakefile_jd", line 26, in __rule_results
  File "/Users/jacda119/anaconda3/lib/python3.7/concurrent/futures/thread.py", line 57, in run
Removing output files of failed job results since they might be corrupted:
results/results.txt
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: /Users/jacda119/git/coderefinery/word-count/.snakemake/log/2018-12-05T103710.244962.snakemake.log
